# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mytest/db/db.ui'
#
# Created: Sun Feb  7 19:13:20 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(546, 528)
        MainWindow.setMinimumSize(QtCore.QSize(546, 528))
        MainWindow.setMaximumSize(QtCore.QSize(546, 528))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(123, 119, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 255, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 255, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 119, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 255, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 255, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 119, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 255, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("test.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 546, 526))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(178, 239, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 239, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 239, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.append = QtGui.QPushButton(self.tab1)
        self.append.setGeometry(QtCore.QRect(415, 360, 116, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(162, 153, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 153, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 153, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.append.setPalette(palette)
        self.append.setObjectName("append")
        self.tableView = QtGui.QTableView(self.tab1)
        self.tableView.setEnabled(True)
        self.tableView.setGeometry(QtCore.QRect(5, 10, 531, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(250, 255, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 255, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tableView.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Nimbus Sans L")
        font.setWeight(75)
        font.setBold(True)
        self.tableView.setFont(font)
        self.tableView.setAcceptDrops(False)
        self.tableView.setFrameShadow(QtGui.QFrame.Plain)
        self.tableView.setLineWidth(3)
        self.tableView.setMidLineWidth(1)
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableView.setDragEnabled(True)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.frame = QtGui.QFrame(self.tab1)
        self.frame.setGeometry(QtCore.QRect(10, 395, 296, 91))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(15, 15, 121, 11))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(15, 35, 111, 18))
        self.label_13.setObjectName("label_13")
        self.rashod_100 = QtGui.QLineEdit(self.frame)
        self.rashod_100.setEnabled(False)
        self.rashod_100.setGeometry(QtCore.QRect(165, 10, 113, 21))
        self.rashod_100.setReadOnly(True)
        self.rashod_100.setObjectName("rashod_100")
        self.full_summa = QtGui.QLineEdit(self.frame)
        self.full_summa.setEnabled(False)
        self.full_summa.setGeometry(QtCore.QRect(160, 50, 113, 21))
        self.full_summa.setReadOnly(True)
        self.full_summa.setObjectName("full_summa")
        self.start = QtGui.QLabel(self.frame)
        self.start.setGeometry(QtCore.QRect(40, 50, 81, 18))
        font = QtGui.QFont()
        font.setFamily("Nimbus Sans L")
        font.setWeight(75)
        font.setBold(True)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.end = QtGui.QLabel(self.frame)
        self.end.setGeometry(QtCore.QRect(40, 65, 81, 18))
        font = QtGui.QFont()
        font.setFamily("Nimbus Sans L")
        font.setWeight(75)
        font.setBold(True)
        self.end.setFont(font)
        self.end.setObjectName("end")
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(15, 65, 21, 18))
        self.label_16.setObjectName("label_16")
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(15, 50, 21, 18))
        self.label_12.setObjectName("label_12")
        self.data = QtGui.QLineEdit(self.tab1)
        self.data.setGeometry(QtCore.QRect(10, 365, 96, 26))
        self.data.setObjectName("data")
        self.dist = QtGui.QLineEdit(self.tab1)
        self.dist.setGeometry(QtCore.QRect(105, 365, 81, 26))
        self.dist.setObjectName("dist")
        self.litres = QtGui.QLineEdit(self.tab1)
        self.litres.setGeometry(QtCore.QRect(185, 365, 76, 26))
        self.litres.setObjectName("litres")
        self.price = QtGui.QLineEdit(self.tab1)
        self.price.setGeometry(QtCore.QRect(260, 365, 71, 26))
        self.price.setObjectName("price")
        self.summa = QtGui.QLineEdit(self.tab1)
        self.summa.setGeometry(QtCore.QRect(330, 365, 76, 26))
        self.summa.setObjectName("summa")
        self.label_6 = QtGui.QLabel(self.tab1)
        self.label_6.setGeometry(QtCore.QRect(35, 345, 41, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.tab1)
        self.label_7.setGeometry(QtCore.QRect(105, 345, 76, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tab1)
        self.label_8.setGeometry(QtCore.QRect(200, 345, 51, 18))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.tab1)
        self.label_9.setGeometry(QtCore.QRect(275, 345, 41, 18))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.tab1)
        self.label_10.setGeometry(QtCore.QRect(350, 345, 51, 18))
        self.label_10.setObjectName("label_10")
        self.frame_2 = QtGui.QFrame(self.tab1)
        self.frame_2.setGeometry(QtCore.QRect(315, 395, 221, 91))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.data_del = QtGui.QLineEdit(self.frame_2)
        self.data_del.setGeometry(QtCore.QRect(10, 40, 113, 26))
        self.data_del.setObjectName("data_del")
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(50, 20, 36, 10))
        self.label_14.setObjectName("label_14")
        self.del_row = QtGui.QPushButton(self.frame_2)
        self.del_row.setGeometry(QtCore.QRect(130, 40, 76, 26))
        self.del_row.setObjectName("del_row")
        self.frame_3 = QtGui.QFrame(self.tab1)
        self.frame_3.setGeometry(QtCore.QRect(10, 300, 526, 41))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.notes = QtGui.QLineEdit(self.frame_3)
        self.notes.setEnabled(False)
        self.notes.setGeometry(QtCore.QRect(140, 10, 113, 21))
        self.notes.setReadOnly(True)
        self.notes.setObjectName("notes")
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(15, 10, 106, 21))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtGui.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(265, 5, 256, 36))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")
        self.lineEdit = QtGui.QLineEdit(self.tab2)
        self.lineEdit.setGeometry(QtCore.QRect(80, 30, 351, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtGui.QLineEdit(self.tab2)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 70, 151, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtGui.QLineEdit(self.tab2)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 110, 151, 26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtGui.QLineEdit(self.tab2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 250, 431, 26))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtGui.QPushButton(self.tab2)
        self.pushButton.setGeometry(QtCore.QRect(120, 170, 131, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.tab2)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 70, 90, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtGui.QLabel(self.tab2)
        self.label.setGeometry(QtCore.QRect(130, 220, 51, 18))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.tab2)
        self.label_2.setGeometry(QtCore.QRect(200, 220, 151, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.tab2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 62, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.tab2)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.tab2)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 51, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtGui.QPushButton(self.tab2)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 170, 121, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Клиент БД Firebird v1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.append.setText(QtGui.QApplication.translate("MainWindow", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Расход на 100 км", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Общая сумма", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.end.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "по", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "  с", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Дистанция", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Литры", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Сумма", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.del_row.setText(QtGui.QApplication.translate("MainWindow", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Всего записей", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Python + QT + Firebird", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "Таблица", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Подключить", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Сохранить", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Статус", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Нет подключения", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Файл БД", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Имя", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Пароль", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Отключить", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "Настройки", None, QtGui.QApplication.UnicodeUTF8))

