# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backup.ui'
#
# Created: Wed Aug 31 15:47:19 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 523)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 132, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 15, 185, 162))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_isp = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_isp.setObjectName("comboBox_isp")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_isp, 0, 1, 1, 1)
        self.comboBox_scp = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_scp.setEnabled(False)
        self.comboBox_scp.setObjectName("comboBox_scp")
        self.comboBox_scp.addItem("")
        self.comboBox_scp.addItem("")
        self.comboBox_scp.addItem("")
        self.comboBox_scp.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_scp, 1, 1, 1, 1)
        self.comboBox_spl = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_spl.setEnabled(False)
        self.comboBox_spl.setObjectName("comboBox_spl")
        self.comboBox_spl.addItem("")
        self.comboBox_spl.addItem("")
        self.comboBox_spl.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_spl, 2, 1, 1, 1)
        self.radioButton_isp = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_isp.setChecked(True)
        self.radioButton_isp.setObjectName("radioButton_isp")
        self.gridLayout_2.addWidget(self.radioButton_isp, 0, 0, 1, 1)
        self.radioButton_scp = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_scp.setObjectName("radioButton_scp")
        self.gridLayout_2.addWidget(self.radioButton_scp, 1, 0, 1, 1)
        self.radioButton_spl = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_spl.setObjectName("radioButton_spl")
        self.gridLayout_2.addWidget(self.radioButton_spl, 2, 0, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setText("")
        self.radioButton_4.setCheckable(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_2.addWidget(self.radioButton_4, 3, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_2.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(5, 260, 551, 256))
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtGui.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(5, 5, 541, 246))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 2, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 3, 1, 1)
        self.tableWidget_3 = QtGui.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableWidget_3, 0, 4, 1, 1)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 190, 86, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_5 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_3 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(415, 225, 96, 27))
        self.pushButton.setObjectName("pushButton")
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setEnabled(False)
        self.widget_2.setGeometry(QtCore.QRect(295, 10, 266, 146))
        self.widget_2.setObjectName("widget_2")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.widget_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(5, 5, 256, 136))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(5, -1, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 225, 93, 27))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.radioButton_isp, QtCore.SIGNAL("toggled(bool)"), self.comboBox_isp.setEnabled)
        QtCore.QObject.connect(self.radioButton_scp, QtCore.SIGNAL("toggled(bool)"), self.comboBox_scp.setEnabled)
        QtCore.QObject.connect(self.radioButton_spl, QtCore.SIGNAL("toggled(bool)"), self.comboBox_spl.setEnabled)
        QtCore.QObject.connect(self.radioButton_5, QtCore.SIGNAL("toggled(bool)"), self.widget.setEnabled)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL("toggled(bool)"), self.widget_2.setEnabled)
        QtCore.QObject.connect(self.radioButton_5, QtCore.SIGNAL("toggled(bool)"), self.pushButton_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Form", "Восстановить", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Form", "Выдать", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(0, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(1, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(2, QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(3, QtGui.QApplication.translate("Form", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(4, QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(5, QtGui.QApplication.translate("Form", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(6, QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(7, QtGui.QApplication.translate("Form", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(8, QtGui.QApplication.translate("Form", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(9, QtGui.QApplication.translate("Form", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(10, QtGui.QApplication.translate("Form", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(11, QtGui.QApplication.translate("Form", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(12, QtGui.QApplication.translate("Form", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(13, QtGui.QApplication.translate("Form", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(14, QtGui.QApplication.translate("Form", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(15, QtGui.QApplication.translate("Form", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(16, QtGui.QApplication.translate("Form", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(17, QtGui.QApplication.translate("Form", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(18, QtGui.QApplication.translate("Form", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(19, QtGui.QApplication.translate("Form", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(20, QtGui.QApplication.translate("Form", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(21, QtGui.QApplication.translate("Form", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(22, QtGui.QApplication.translate("Form", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scp.setItemText(0, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scp.setItemText(1, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scp.setItemText(2, QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scp.setItemText(3, QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_spl.setItemText(0, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_spl.setItemText(1, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_spl.setItemText(2, QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_isp.setText(QtGui.QApplication.translate("Form", "ISP", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_scp.setText(QtGui.QApplication.translate("Form", "cPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_spl.setText(QtGui.QApplication.translate("Form", "Plesk", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Users", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 1).setText(QtGui.QApplication.translate("Form", "u1234567", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget_2.setSortingEnabled(True)
        self.tableWidget_2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Sites", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.item(0, 1).setText(QtGui.QApplication.translate("Form", "test.ru", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tableWidget_3.setSortingEnabled(True)
        self.tableWidget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Bases", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.item(0, 1).setText(QtGui.QApplication.translate("Form", "u1234567_test", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.radioButton_5.setText(QtGui.QApplication.translate("Form", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Form", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Site", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))

