# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'srv.ui'
#
# Created: Wed Aug 31 12:57:43 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 503)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(15, 5, 711, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 1, 1, 1)
        self.textEdit_2 = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 5, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 5, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_isp = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_isp.setObjectName("comboBox_isp")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.comboBox_isp.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_isp, 0, 1, 1, 1)
        self.comboBox_scp = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_scp.setEnabled(False)
        self.comboBox_scp.setObjectName("comboBox_scp")
        self.comboBox_scp.addItem("")
        self.comboBox_scp.addItem("")
        self.comboBox_scp.addItem("")
        self.comboBox_scp.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_scp, 1, 1, 1, 1)
        self.comboBox_spl = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_spl.setEnabled(False)
        self.comboBox_spl.setObjectName("comboBox_spl")
        self.comboBox_spl.addItem("")
        self.comboBox_spl.addItem("")
        self.comboBox_spl.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_spl, 2, 1, 1, 1)
        self.radioButton_isp = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_isp.setChecked(True)
        self.radioButton_isp.setObjectName("radioButton_isp")
        self.gridLayout_2.addWidget(self.radioButton_isp, 0, 0, 1, 1)
        self.radioButton_scp = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_scp.setObjectName("radioButton_scp")
        self.gridLayout_2.addWidget(self.radioButton_scp, 1, 0, 1, 1)
        self.radioButton_spl = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_spl.setObjectName("radioButton_spl")
        self.gridLayout_2.addWidget(self.radioButton_spl, 2, 0, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setText("")
        self.radioButton_4.setCheckable(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_2.addWidget(self.radioButton_4, 3, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_2.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 731, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuBackup = QtGui.QMenu(self.menuBar)
        self.menuBackup.setObjectName("menuBackup")
        MainWindow.setMenuBar(self.menuBar)
        self.actionRestore = QtGui.QAction(MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.actionCreate = QtGui.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.menuBackup.addAction(self.actionRestore)
        self.menuBackup.addAction(self.actionCreate)
        self.menuBar.addAction(self.menuBackup.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.radioButton_scp, QtCore.SIGNAL("toggled(bool)"), self.comboBox_scp.setEnabled)
        QtCore.QObject.connect(self.radioButton_spl, QtCore.SIGNAL("toggled(bool)"), self.comboBox_spl.setEnabled)
        QtCore.QObject.connect(self.radioButton_isp, QtCore.SIGNAL("toggled(bool)"), self.comboBox_isp.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "srv_cmd_executor v1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "cmd:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Server answers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Commands:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("MainWindow", "No connection", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(2, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(3, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(4, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(5, QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(6, QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(7, QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(8, QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(9, QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(10, QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(11, QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(12, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(13, QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(14, QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(15, QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(16, QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(17, QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(18, QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(19, QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(20, QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(21, QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_isp.setItemText(22, QtGui.QApplication.translate("MainWindow", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scp.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scp.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scp.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_scp.setItemText(3, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_spl.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_spl.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_spl.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_isp.setText(QtGui.QApplication.translate("MainWindow", "ISP", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_scp.setText(QtGui.QApplication.translate("MainWindow", "cPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_spl.setText(QtGui.QApplication.translate("MainWindow", "Plesk", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBackup.setTitle(QtGui.QApplication.translate("MainWindow", "backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestore.setText(QtGui.QApplication.translate("MainWindow", "restore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate.setText(QtGui.QApplication.translate("MainWindow", "create", None, QtGui.QApplication.UnicodeUTF8))

