# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created: Wed Jan 20 20:01:12 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(393, 327)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.town = QtGui.QLabel(self.centralwidget)
        self.town.setGeometry(QtCore.QRect(20, 15, 62, 18))
        self.town.setObjectName("town")
        self.latitude = QtGui.QLabel(self.centralwidget)
        self.latitude.setGeometry(QtCore.QRect(20, 40, 62, 18))
        self.latitude.setObjectName("latitude")
        self.longitude = QtGui.QLabel(self.centralwidget)
        self.longitude.setGeometry(QtCore.QRect(20, 65, 62, 18))
        self.longitude.setObjectName("longitude")
        self.lat = QtGui.QLabel(self.centralwidget)
        self.lat.setGeometry(QtCore.QRect(100, 40, 62, 18))
        self.lat.setObjectName("lat")
        self.long_2 = QtGui.QLabel(self.centralwidget)
        self.long_2.setGeometry(QtCore.QRect(100, 65, 62, 18))
        self.long_2.setObjectName("long_2")
        self.weekday = QtGui.QLabel(self.centralwidget)
        self.weekday.setGeometry(QtCore.QRect(305, 35, 66, 16))
        self.weekday.setObjectName("weekday")
        self.tod = QtGui.QLabel(self.centralwidget)
        self.tod.setGeometry(QtCore.QRect(305, 60, 56, 16))
        self.tod.setObjectName("tod")
        self.date = QtGui.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(300, 10, 76, 18))
        self.date.setObjectName("date")
        self.weather = QtGui.QLabel(self.centralwidget)
        self.weather.setGeometry(QtCore.QRect(75, 100, 62, 18))
        self.weather.setObjectName("weather")
        self.cloudiness = QtGui.QLabel(self.centralwidget)
        self.cloudiness.setGeometry(QtCore.QRect(30, 125, 86, 18))
        self.cloudiness.setObjectName("cloudiness")
        self.precipitation = QtGui.QLabel(self.centralwidget)
        self.precipitation.setGeometry(QtCore.QRect(30, 155, 62, 16))
        self.precipitation.setObjectName("precipitation")
        self.rpower = QtGui.QLabel(self.centralwidget)
        self.rpower.setGeometry(QtCore.QRect(30, 185, 116, 16))
        self.rpower.setObjectName("rpower")
        self.relwet = QtGui.QLabel(self.centralwidget)
        self.relwet.setGeometry(QtCore.QRect(155, 185, 62, 18))
        self.relwet.setObjectName("relwet")
        self.pressure = QtGui.QLabel(self.centralwidget)
        self.pressure.setGeometry(QtCore.QRect(30, 245, 76, 18))
        self.pressure.setObjectName("pressure")
        self.temperature = QtGui.QLabel(self.centralwidget)
        self.temperature.setGeometry(QtCore.QRect(270, 165, 96, 16))
        self.temperature.setObjectName("temperature")
        self.prec = QtGui.QLabel(self.centralwidget)
        self.prec.setGeometry(QtCore.QRect(130, 155, 106, 18))
        self.prec.setObjectName("prec")
        self.cldn = QtGui.QLabel(self.centralwidget)
        self.cldn.setGeometry(QtCore.QRect(130, 125, 116, 18))
        self.cldn.setObjectName("cldn")
        self.pres_min = QtGui.QLabel(self.centralwidget)
        self.pres_min.setGeometry(QtCore.QRect(110, 250, 26, 10))
        self.pres_min.setObjectName("pres_min")
        self.update = QtGui.QPushButton(self.centralwidget)
        self.update.setGeometry(QtCore.QRect(295, 285, 81, 27))
        self.update.setObjectName("update")
        self.pres_max = QtGui.QLabel(self.centralwidget)
        self.pres_max.setGeometry(QtCore.QRect(160, 250, 26, 10))
        self.pres_max.setObjectName("pres_max")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(145, 250, 21, 10))
        self.label_5.setObjectName("label_5")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 250, 62, 10))
        self.label.setObjectName("label")
        self.temp_min = QtGui.QProgressBar(self.centralwidget)
        self.temp_min.setGeometry(QtCore.QRect(290, 190, 16, 71))
        self.temp_min.setMinimum(-40)
        self.temp_min.setMaximum(40)
        self.temp_min.setProperty("value", QtCore.QVariant(-1))
        self.temp_min.setOrientation(QtCore.Qt.Vertical)
        self.temp_min.setObjectName("temp_min")
        self.temp_max = QtGui.QProgressBar(self.centralwidget)
        self.temp_max.setGeometry(QtCore.QRect(320, 190, 16, 71))
        self.temp_max.setMinimum(-40)
        self.temp_max.setMaximum(40)
        self.temp_max.setProperty("value", QtCore.QVariant(-1))
        self.temp_max.setOrientation(QtCore.Qt.Vertical)
        self.temp_max.setObjectName("temp_max")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 85, 371, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(272, 5, 16, 86))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(275, 115, 46, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("larrow.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 115, 51, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("rarrow.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Сводка погоды v1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.town.setText(QtGui.QApplication.translate("MainWindow", "Самара", None, QtGui.QApplication.UnicodeUTF8))
        self.latitude.setText(QtGui.QApplication.translate("MainWindow", "Широта", None, QtGui.QApplication.UnicodeUTF8))
        self.longitude.setText(QtGui.QApplication.translate("MainWindow", "Долгота", None, QtGui.QApplication.UnicodeUTF8))
        self.lat.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.long_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.weekday.setText(QtGui.QApplication.translate("MainWindow", "Суббота", None, QtGui.QApplication.UnicodeUTF8))
        self.tod.setText(QtGui.QApplication.translate("MainWindow", "Вечер", None, QtGui.QApplication.UnicodeUTF8))
        self.date.setText(QtGui.QApplication.translate("MainWindow", "16.01.2010", None, QtGui.QApplication.UnicodeUTF8))
        self.weather.setText(QtGui.QApplication.translate("MainWindow", "Условия", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudiness.setText(QtGui.QApplication.translate("MainWindow", "Облачность", None, QtGui.QApplication.UnicodeUTF8))
        self.precipitation.setText(QtGui.QApplication.translate("MainWindow", "Осадки", None, QtGui.QApplication.UnicodeUTF8))
        self.rpower.setText(QtGui.QApplication.translate("MainWindow", "Отн. влажность", None, QtGui.QApplication.UnicodeUTF8))
        self.relwet.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pressure.setText(QtGui.QApplication.translate("MainWindow", "Давление", None, QtGui.QApplication.UnicodeUTF8))
        self.temperature.setText(QtGui.QApplication.translate("MainWindow", "Температура", None, QtGui.QApplication.UnicodeUTF8))
        self.prec.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.cldn.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_min.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.update.setText(QtGui.QApplication.translate("MainWindow", "Обновить", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_max.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "мм р.ст.", None, QtGui.QApplication.UnicodeUTF8))
        self.temp_min.setFormat(QtGui.QApplication.translate("MainWindow", "%v", None, QtGui.QApplication.UnicodeUTF8))
        self.temp_max.setFormat(QtGui.QApplication.translate("MainWindow", "%v", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))

